# Generated by Django 4.1.1 on 2022-10-23 09:14

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("slug", autoslug.fields.AutoSlugField(editable=False, populate_from="title", unique=True)),
                ("gallery_date", models.DateField(blank=True, help_text="Date of the gallery. Optional.", null=True)),
            ],
            options={
                "verbose_name": "Gallery",
                "verbose_name_plural": "Galleries",
            },
        ),
    ]
