# Generated by Django 4.1.1 on 2022-10-23 09:14

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", ckeditor.fields.RichTextField(blank=True)),
                ("external_url", models.URLField(blank=True, help_text="Optional")),
                ("slug", autoslug.fields.AutoSlugField(editable=False, null=True, populate_from="name", unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectSupervisor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name for this person if they do not have a profile.",
                        max_length=255,
                        verbose_name="Name override",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional profile to link to for this person",
                        null=True,
                        on_delete=projects.models.PERSON_PROFILE_SET_NULL_SAFE,
                        to="profiles.baseprofilemodel",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="projects.project"
                    ),
                ),
            ],
            options={
                "verbose_name": "Supervisor",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name for this person if they do not have a profile.",
                        max_length=255,
                        verbose_name="Name override",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional profile to link to for this person",
                        null=True,
                        on_delete=projects.models.PERSON_PROFILE_SET_NULL_SAFE,
                        to="profiles.baseprofilemodel",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="projects.project"
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant",
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="projectsupervisor",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("profile__isnull", True), models.Q(("name__exact", ""), _negated=True)),
                    models.Q(("profile__isnull", False), ("name__exact", "")),
                    models.Q(("profile__isnull", False), models.Q(("name__exact", ""), _negated=True)),
                    _connector="OR",
                ),
                name="projects_projectsupervisor_name_or_profile",
                violation_error_message="A profile and/or name must be provided",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectparticipant",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("profile__isnull", True), models.Q(("name__exact", ""), _negated=True)),
                    models.Q(("profile__isnull", False), ("name__exact", "")),
                    models.Q(("profile__isnull", False), models.Q(("name__exact", ""), _negated=True)),
                    _connector="OR",
                ),
                name="projects_projectparticipant_name_or_profile",
                violation_error_message="A profile and/or name must be provided",
            ),
        ),
    ]
