# Generated by Django 4.1.1 on 2022-10-23 09:14

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", autoslug.fields.AutoSlugField(editable=False, populate_from="title", unique=True)),
                ("title", models.CharField(max_length=255)),
                ("body", ckeditor.fields.RichTextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_date", models.DateTimeField(verbose_name="Event date and time")),
                (
                    "event_date_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="Defaults to 1 hour after start time",
                        null=True,
                        verbose_name="Event end date and time",
                    ),
                ),
                (
                    "registration_url",
                    models.URLField(blank=True, help_text="URL to register for the event. Optional.", null=True),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to an external page for further event information. Optional.",
                        null=True,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="eventmodel",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("event_date_end__isnull", True), ("event_date_end__gte", models.F("event_date")), _connector="OR"
                ),
                name="end_date must be greater than or equal to start_date",
                violation_error_message="Event end date must be greater than or equal to the event start date.",
            ),
        ),
    ]
