# Generated by Django 4.1.1 on 2022-10-23 09:14

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseProfileModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("biography", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="")),
                ("external_url", models.URLField(blank=True, null=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique_with=("polymorphic_ctype_id",)
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
            },
        ),
        migrations.CreateModel(
            name="PhDStudentProfileModel",
            fields=[
                (
                    "baseprofilemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="profiles.baseprofilemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "PhD Student Profile",
            },
            bases=("profiles.baseprofilemodel",),
        ),
        migrations.CreateModel(
            name="StaffProfileModel",
            fields=[
                (
                    "baseprofilemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="profiles.baseprofilemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Profile",
            },
            bases=("profiles.baseprofilemodel",),
        ),
    ]
